export enum WalletRoute {
  Wallet = 'Wallet',
  WalletDetails = 'WalletDetails',
  Deposit = 'Deposit',
  DepositDetails = 'DepositDetails',
  Withdraw = 'Withdraw',
  WithdrawDetails = 'WithdrawDetails',
  History = 'History',
  TransactionDetails = 'TransactionDetails',
  TransferUser = 'TransferUser',
  TransferAsset = 'TransferAsset',
  TransferDetails = 'TransferDetails',
  Swap = 'Swap',
  SwapAssets = 'SwapAssets',
  NetworkLogger = 'NetworkLogger',
}
